### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by diemol** [SeleniumHQ/site#8]
Thanks to @barancev, we have a report with broken links https://codepen.io/barancev/full/ZEEpREj.
We should go through it and fix them.

**Comment by boris779** [comment]
If you like I can assist you. split it up or assign me some of the pages.

**Comment by boris779** [comment]
I took a look into the report, but I cannot find any broken links from that report.

e.g. the links from about page to the history are all valid.

These reported links do not exist. The existing links are valid. 
`
https://seleniumhq.github.io/site/about/
	https://seleniumhq.github.io/history
	  \_____ error code: 404 (not found)
	https://seleniumhq.github.io/ecosystem
	  \_____ error code: 404 (not found)

https://seleniumhq.github.io/site/blog/
	https://seleniumhq.github.io/blog
	  \_____ error code: 404 (not found)
	mailto:
	  \_____ error code: 12007 (no such host)
	https://seleniumhq.github.io/blog/2018
	  \_____ error code: 404 (not found)
	https://seleniumhq.github.io/blog/2017
	  \_____ error code: 404 (not found)
	https://seleniumhq.github.io/blog/2016
	  \_____ error code: 404 (not found)
	https://seleniumhq.github.io/blog/2015
	  \_____ error code: 404 (not found)
`

I stopped after these two pages. Maybe @barancev can run the report again.

**Comment by barancev** [comment]
It's quite possible that the site was updated, I'll create a new report and attach it here.

**Comment by diemol** [comment]
Yes, I think I fixed all those broken links. We can reopen this in case someone finds more.
